import Foundation

enum BrowserAssets {
    static let annotationCSS = """
/* Annotate extension — all elements scoped under #annotate-root */
#annotate-root { all: initial; position: fixed; top: 0; left: 0; width: 100vw; height: 100vh; z-index: 2147483647; cursor: crosshair; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif; font-size: 14px; color: #fff; line-height: 1.4; box-sizing: border-box; }
#annotate-root * { box-sizing: border-box; }
#annotate-canvas { all: initial; position: absolute; top: 0; left: 0; width: 100%; height: 100%; cursor: crosshair; }
#annotate-indicator { all: initial; position: fixed; bottom: 24px; right: 24px; width: 40px; height: 40px; background: rgba(30,30,30,0.9); border-radius: 10px; display: flex; align-items: center; justify-content: center; cursor: grab; z-index: 2147483647; box-shadow: 0 2px 8px rgba(0,0,0,0.3); user-select: none; -webkit-user-select: none; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif; }
#annotate-indicator:active { cursor: grabbing; }
#annotate-indicator svg { width: 22px; height: 22px; fill: none; stroke: #fff; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round; }
#annotate-indicator::after { content: \"\"; position: absolute; inset: calc(-2px - var(--annotate-width, 3) * 0.3px); border-radius: calc(12px + var(--annotate-width, 3) * 0.3px); border: calc(1.5px + var(--annotate-width, 3) * 0.15px) solid var(--annotate-color, #ff0000); box-shadow: 0 0 calc(var(--annotate-width, 3) * 0.8px) calc(var(--annotate-width, 3) * 0.3px) var(--annotate-color, #ff0000); pointer-events: none; transition: all 0.15s ease; }
#annotate-root .annotate-text-input { all: initial; position: absolute; min-width: 2px; min-height: 1em; padding: 2px 4px; background: transparent; border: 1px solid rgba(128,128,128,0.6); outline: none; color: var(--annotate-color, #ff0000); font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif; font-size: var(--annotate-font-size, 18px); line-height: 1.3; white-space: pre-wrap; word-break: break-word; cursor: text; z-index: 2147483647; }
#annotate-help { all: initial; position: fixed; inset: 0; display: flex; align-items: center; justify-content: center; background: rgba(0,0,0,0.45); z-index: 2147483647; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif; font-size: 13px; color: #e0e0e0; line-height: 1.5; }
#annotate-help-box { all: initial; background: rgba(30,30,30,0.95); border-radius: 12px; padding: 20px 24px; box-shadow: 0 8px 32px rgba(0,0,0,0.4); font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif; font-size: 13px; color: #e0e0e0; line-height: 1.5; min-width: 220px; }
.annotate-help-title { all: initial; display: block; font-family: inherit; font-size: 15px; font-weight: 600; color: #fff; margin: 0 0 12px; line-height: 1.4; }
.annotate-help-table { all: initial; display: table; font-family: inherit; font-size: 13px; color: #e0e0e0; line-height: 1.5; width: 100%; border-collapse: collapse; }
.annotate-help-table th { all: initial; display: table-cell; font-family: inherit; font-size: 11px; font-weight: 600; color: #888; text-transform: uppercase; letter-spacing: 0.5px; padding: 8px 0 4px; line-height: 1.5; }
.annotate-help-table tr { all: initial; display: table-row; }
.annotate-help-table td { all: initial; display: table-cell; font-family: inherit; font-size: 13px; color: #e0e0e0; padding: 3px 0; line-height: 1.5; vertical-align: middle; }
.annotate-help-table td:first-child { padding-right: 16px; white-space: nowrap; }
.annotate-help-table kbd { all: initial; display: inline-block; font-family: inherit; font-size: 11px; color: #fff; background: rgba(255,255,255,0.12); border: 1px solid rgba(255,255,255,0.2); border-radius: 4px; padding: 1px 6px; line-height: 1.6; }
.annotate-swatch { all: initial; display: inline-block; width: 10px; height: 10px; border-radius: 2px; vertical-align: middle; margin-right: 4px; }
.annotate-help-hint { all: initial; display: block; font-family: inherit; font-size: 11px; color: #666; text-align: center; margin-top: 12px; line-height: 1.5; }
#annotate-dialog { all: initial; position: fixed; bottom: 80px; right: 24px; background: rgba(30,30,30,0.95); border-radius: 12px; padding: 14px 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.45); z-index: 2147483647; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif; font-size: 13px; color: #e0e0e0; line-height: 1.4; min-width: 160px; }
#annotate-dialog p { all: initial; display: block; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif; font-size: 13px; font-weight: 600; color: #fff; margin: 0 0 10px; line-height: 1.4; }
.annotate-dialog-btns { all: initial; display: flex; gap: 8px; margin-bottom: 8px; }
#annotate-dialog button { all: initial; display: inline-block; flex: 1; padding: 6px 0; border-radius: 6px; font-size: 13px; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif; cursor: pointer; font-weight: 500; text-align: center; line-height: 1.4; }
#annotate-dialog .annotate-btn-yes { background: #2563eb; color: #fff; }
#annotate-dialog .annotate-btn-no { background: rgba(255,255,255,0.12); color: #e0e0e0; }
.annotate-dialog-countdown { all: initial; display: block; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif; font-size: 11px; color: #555; text-align: center; line-height: 1.4; }
"""

    static let annotationJS = """
(() => {
  if (window.AnnotateMac?.active) return;
  let tool = 'draw';
  let color = localStorage.getItem('annotate_color') || '#ff0000';
  let lineWidth = parseInt(localStorage.getItem('annotate_lineWidth') || '3', 10);
  let fontSize = 18;
  const actions = [];
  const redoStack = [];
  let drawing = false;
  let dragStart = null;
  let currentPath = [];
  let textEditing = false;
  let activeTextEl = null;
  let allSelected = false;
  let exitDialogTimer = null;
  const ICONS = {
    draw: '<path d="M3 21l1.5-4.5L17.25 3.75a1.06 1.06 0 0 1 1.5 1.5L6 18z"/><path d="M15 6l3 3"/>',
    arrow: '<line x1="5" y1="19" x2="19" y2="5"/><polyline points="10 5 19 5 19 14"/>',
    square: '<rect x="4" y="6" width="16" height="12" fill="none"/>',
    circle: '<ellipse cx="12" cy="12" rx="9" ry="7"/>',
    text: '<text x="12" y="17" text-anchor="middle" fill="#fff" stroke="none" font-size="16" font-weight="bold" font-family="sans-serif">T</text>',
    highlight: '<rect x="3" y="7" width="18" height="10" rx="1" style="fill:#fff;fill-opacity:0.3"/>',
    blackboard: '<rect x="4" y="6" width="16" height="12" rx="1"/><line x1="4" y1="18" x2="20" y2="6"/><line x1="8" y1="18" x2="20" y2="10"/><line x1="4" y1="14" x2="16" y2="6"/>',
    line: '<line x1="5" y1="19" x2="19" y2="5"/>',
    callout: '<circle cx="12" cy="12" r="9"/><text x="12" y="16" text-anchor="middle" style="fill:#fff;stroke:none" font-size="12" font-weight="bold" font-family="sans-serif">1</text>'
  };
  const root = document.createElement('div');
  root.id = 'annotate-root';
  const canvas = document.createElement('canvas');
  canvas.id = 'annotate-canvas';
  root.appendChild(canvas);
  const ctx = canvas.getContext('2d');
  const indicator = document.createElement('div');
  indicator.id = 'annotate-indicator';
  indicator.innerHTML = `<svg viewBox="0 0 24 24">${ICONS[tool]}</svg>`;
  root.appendChild(indicator);
  document.documentElement.appendChild(root);
  function updateIndicatorColor(){ indicator.style.setProperty('--annotate-color', color); }
  function updateIndicatorWidth(){ const val = tool === 'text' ? (fontSize - 8) / 64 * 19 + 1 : lineWidth; indicator.style.setProperty('--annotate-width', val); }
  updateIndicatorColor(); updateIndicatorWidth();
  function sizeCanvas(){ const dpr = window.devicePixelRatio || 1; canvas.width = window.innerWidth * dpr; canvas.height = window.innerHeight * dpr; canvas.style.width = window.innerWidth + 'px'; canvas.style.height = window.innerHeight + 'px'; ctx.setTransform(dpr,0,0,dpr,0,0); replayAll(); }
  function drawArrow(c,x1,y1,x2,y2,lw){ const headLen=Math.max(lw*4,12); const angle=Math.atan2(y2-y1,x2-x1); c.beginPath(); c.moveTo(x1,y1); c.lineTo(x2,y2); c.stroke(); c.beginPath(); c.moveTo(x2,y2); c.lineTo(x2-headLen*Math.cos(angle-Math.PI/6), y2-headLen*Math.sin(angle-Math.PI/6)); c.lineTo(x2-headLen*Math.cos(angle+Math.PI/6), y2-headLen*Math.sin(angle+Math.PI/6)); c.closePath(); c.fill(); }
  function renderAction(a){ ctx.save(); ctx.strokeStyle=a.color; ctx.fillStyle=a.color; ctx.lineWidth=a.lineWidth || lineWidth; ctx.lineCap='round'; ctx.lineJoin='round'; if(a.type==='draw'){ if(a.points.length<2){ ctx.beginPath(); ctx.arc(a.points[0].x,a.points[0].y,(a.lineWidth||lineWidth)/2,0,Math.PI*2); ctx.fill(); } else { ctx.beginPath(); ctx.moveTo(a.points[0].x,a.points[0].y); for(let i=1;i<a.points.length;i++) ctx.lineTo(a.points[i].x,a.points[i].y); ctx.stroke(); } } else if(a.type==='arrow'){ drawArrow(ctx,a.x1,a.y1,a.x2,a.y2,a.lineWidth||lineWidth); } else if(a.type==='square'){ const x=Math.min(a.x1,a.x2), y=Math.min(a.y1,a.y2), w=Math.abs(a.x2-a.x1), h=Math.abs(a.y2-a.y1); if(w>0&&h>0){ ctx.beginPath(); ctx.rect(x,y,w,h); ctx.stroke(); } } else if(a.type==='circle'){ const cx=(a.x1+a.x2)/2, cy=(a.y1+a.y2)/2, rx=Math.abs(a.x2-a.x1)/2, ry=Math.abs(a.y2-a.y1)/2; if(rx>0&&ry>0){ ctx.beginPath(); ctx.ellipse(cx,cy,rx,ry,0,0,Math.PI*2); ctx.stroke(); } } else if(a.type==='text'){ ctx.font=`${a.fontSize}px -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif`; ctx.fillStyle=a.color; ctx.textBaseline='top'; const lines=a.text.split('\\n'); for(let i=0;i<lines.length;i++) ctx.fillText(lines[i], a.x, a.y + i * a.fontSize * 1.3); } else if(a.type==='highlight'){ const x=Math.min(a.x1,a.x2), y=Math.min(a.y1,a.y2), w=Math.abs(a.x2-a.x1), h=Math.abs(a.y2-a.y1); if(w>0&&h>0){ ctx.globalAlpha=0.4; ctx.fillStyle=a.color; ctx.fillRect(x,y,w,h); } } else if(a.type==='blackboard'){ const x=Math.min(a.x1,a.x2), y=Math.min(a.y1,a.y2), w=Math.abs(a.x2-a.x1), h=Math.abs(a.y2-a.y1); if(w>0&&h>0){ ctx.fillStyle='#1a1a1a'; ctx.fillRect(x,y,w,h); } } else if(a.type==='line'){ ctx.beginPath(); ctx.moveTo(a.x1,a.y1); ctx.lineTo(a.x2,a.y2); ctx.stroke(); } else if(a.type==='callout'){ ctx.beginPath(); ctx.arc(a.x,a.y,a.radius,0,Math.PI*2); ctx.fillStyle=a.color; ctx.fill(); ctx.fillStyle='#fff'; ctx.font=`bold ${Math.round(a.radius*1.1)}px -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif`; ctx.textAlign='center'; ctx.textBaseline='middle'; ctx.fillText(String(a.n), a.x, a.y); } ctx.restore(); }
  function replayAll(){ ctx.clearRect(0,0,canvas.width,canvas.height); for(const a of actions) renderAction(a); if(allSelected&&actions.length>0){ ctx.save(); ctx.fillStyle='rgba(59, 130, 246, 0.15)'; ctx.fillRect(0,0,canvas.width,canvas.height); ctx.restore(); } }
  function getPos(e){ return {x:e.clientX,y:e.clientY}; }
  function setTool(t){ if(textEditing) commitText(); tool=t; indicator.innerHTML=`<svg viewBox=\"0 0 24 24\">${ICONS[tool]}</svg>`; canvas.style.cursor = tool === 'text' ? 'text' : 'crosshair'; updateIndicatorWidth(); }
  function setColor(c){ color=c; localStorage.setItem('annotate_color', c); updateIndicatorColor(); }
  function startTextInput(x,y){ if(textEditing) commitText(); const el=document.createElement('div'); el.className='annotate-text-input'; el.contentEditable='true'; el.style.left=(x-5)+'px'; el.style.top=(y-3-Math.round(fontSize*0.65))+'px'; el.style.setProperty('--annotate-color', color); el.style.setProperty('--annotate-font-size', fontSize+'px'); el.style.color=color; el.style.fontSize=fontSize+'px'; root.appendChild(el); requestAnimationFrame(()=>{ el.focus(); const sel=window.getSelection(); const range=document.createRange(); range.selectNodeContents(el); range.collapse(true); sel.removeAllRanges(); sel.addRange(range); }); textEditing=true; activeTextEl=el; el.addEventListener('keydown',(e)=>{ if(e.key==='Enter'&&!e.shiftKey){ e.preventDefault(); commitText(); } else if(e.key==='Escape'){ e.preventDefault(); cancelText(); } e.stopPropagation(); }); function onClickOutside(e){ if(!el.contains(e.target)){ e.stopPropagation(); commitText(); document.removeEventListener('mousedown', onClickOutside, true); } } setTimeout(()=>document.addEventListener('mousedown', onClickOutside, true),0); }
  function cancelText(){ if(!activeTextEl) return; activeTextEl.remove(); activeTextEl=null; textEditing=false; }
  function commitText(){ if(!activeTextEl) return; const text=activeTextEl.innerText.trim(); if(text){ const rect=activeTextEl.getBoundingClientRect(); actions.push({ type:'text', text, x:rect.left+5, y:rect.top+3+Math.round(fontSize*0.15), fontSize, color:activeTextEl.style.color, lineWidth }); redoStack.length=0; replayAll(); } activeTextEl.remove(); activeTextEl=null; textEditing=false; }
  function placeCallout(x,y){ const n=actions.filter(a=>a.type==='callout').length+1; const radius=Math.max(12,lineWidth*3); actions.push({type:'callout', x,y,n,color,radius}); redoStack.length=0; replayAll(); }
  function enterSelectAll(){ allSelected=true; replayAll(); if(!document.getElementById('annotate-select-hint')){ const hint=document.createElement('div'); hint.id='annotate-select-hint'; hint.textContent='All annotations selected — Delete to clear, Esc to cancel'; hint.style.cssText='all:initial;position:fixed;top:16px;left:50%;transform:translateX(-50%);background:rgba(30,30,30,0.92);color:#fff;font:13px/1 -apple-system,BlinkMacSystemFont,sans-serif;padding:8px 16px;border-radius:8px;z-index:2147483647;pointer-events:none;white-space:nowrap;box-shadow:0 2px 8px rgba(0,0,0,0.35)'; root.appendChild(hint); } }
  function exitSelectAll(){ allSelected=false; const hint=document.getElementById('annotate-select-hint'); if(hint) hint.remove(); replayAll(); }
  function showHelpPopup(){ if(document.getElementById('annotate-help')) return; const help=document.createElement('div'); help.id='annotate-help'; help.innerHTML=`<div id=\"annotate-help-box\"><div class=\"annotate-help-title\">Annotate — Shortcuts</div><table class=\"annotate-help-table\"><tr><th colspan=\"2\">Tools</th></tr><tr><td><kbd>D</kbd></td><td>Draw</td></tr><tr><td><kbd>A</kbd></td><td>Arrow</td></tr><tr><td><kbd>L</kbd></td><td>Line</td></tr><tr><td><kbd>S</kbd></td><td>Square</td></tr><tr><td><kbd>C</kbd></td><td>Circle</td></tr><tr><td><kbd>H</kbd></td><td>Highlight</td></tr><tr><td><kbd>B</kbd></td><td>Blackboard</td></tr><tr><td><kbd>F</kbd></td><td>Text</td></tr><tr><td><kbd>N</kbd></td><td>Number callout</td></tr><tr><th colspan=\"2\">Colors</th></tr><tr><td><kbd>1</kbd></td><td><span class=\"annotate-swatch\" style=\"background:#ff0000\"></span> Red</td></tr><tr><td><kbd>2</kbd></td><td><span class=\"annotate-swatch\" style=\"background:#2563eb\"></span> Blue</td></tr><tr><td><kbd>3</kbd></td><td><span class=\"annotate-swatch\" style=\"background:#16a34a\"></span> Green</td></tr><tr><td><kbd>4</kbd></td><td><span class=\"annotate-swatch\" style=\"background:#eab308\"></span> Yellow</td></tr><tr><td><kbd>5</kbd></td><td><span class=\"annotate-swatch\" style=\"background:#d1d5db;border:1px solid #9ca3af\"></span> Light Grey</td></tr><tr><td><kbd>6</kbd></td><td><span class=\"annotate-swatch\" style=\"background:#6b7280\"></span> Dark Grey</td></tr><tr><th colspan=\"2\">Other</th></tr><tr><td><kbd>R</kbd> <kbd>E</kbd></td><td>Line width / font size</td></tr><tr><td><kbd>⌘+Z</kbd></td><td>Undo</td></tr><tr><td><kbd>⌘+Y</kbd></td><td>Redo</td></tr><tr><td><kbd>⌘+A</kbd></td><td>Select all → Delete to clear</td></tr><tr><td><kbd>Esc</kbd></td><td>Exit</td></tr></table><div class=\"annotate-help-hint\">Click anywhere to dismiss</div></div>`; root.appendChild(help); function dismiss(e){ e.stopPropagation(); help.remove(); document.removeEventListener('mousedown', dismiss, true); } setTimeout(()=>document.addEventListener('mousedown', dismiss, true),0); }
  function clearExitDialog(){ clearInterval(exitDialogTimer); exitDialogTimer=null; const d=document.getElementById('annotate-dialog'); if(d) d.remove(); }
  function teardown(){ document.removeEventListener('keydown', onKeyDown, true); window.removeEventListener('resize', sizeCanvas); root.remove(); const style=document.getElementById('annotate-mac-style'); if(style) style.remove(); delete window.AnnotateMac; }
  function showExitDialog(){ if(document.getElementById('annotate-dialog')) return; const dialog=document.createElement('div'); dialog.id='annotate-dialog'; dialog.innerHTML=`<p>Exit annotate mode?</p><div class=\"annotate-dialog-btns\"><button class=\"annotate-btn-yes\">Stay</button><button class=\"annotate-btn-no\">Exit</button></div><div class=\"annotate-dialog-countdown\">Exiting in 4s</div>`; root.appendChild(dialog); let remaining=4; const countdownEl=dialog.querySelector('.annotate-dialog-countdown'); exitDialogTimer=setInterval(()=>{ remaining--; if(remaining<=0){ clearExitDialog(); teardown(); } else { countdownEl.textContent=`Exiting in ${remaining}s`; } },1000); dialog.querySelector('.annotate-btn-yes').addEventListener('click',()=>clearExitDialog()); dialog.querySelector('.annotate-btn-no').addEventListener('click',()=>{ clearExitDialog(); teardown(); }); }
  function onMouseDown(e){ if(e.button!==0) return; if(allSelected) exitSelectAll(); if(tool==='text'){ startTextInput(e.clientX,e.clientY); return; } if(tool==='callout'){ placeCallout(e.clientX,e.clientY); return; } drawing=true; dragStart=getPos(e); if(tool==='draw') currentPath=[dragStart]; }
  function onMouseMove(e){ if(!drawing) return; const pos=getPos(e); if(tool==='draw'){ currentPath.push(pos); ctx.save(); ctx.strokeStyle=color; ctx.lineWidth=lineWidth; ctx.lineCap='round'; ctx.lineJoin='round'; ctx.beginPath(); const prev=currentPath[currentPath.length-2]; ctx.moveTo(prev.x, prev.y); ctx.lineTo(pos.x,pos.y); ctx.stroke(); ctx.restore(); } else if(['arrow','square','circle','line','highlight','blackboard'].includes(tool)){ replayAll(); ctx.save(); ctx.strokeStyle=color; ctx.fillStyle=color; ctx.lineWidth=lineWidth; ctx.lineCap='round'; ctx.lineJoin='round'; if(tool==='arrow'){ drawArrow(ctx, dragStart.x, dragStart.y, pos.x, pos.y, lineWidth); } else if(tool==='line'){ ctx.beginPath(); ctx.moveTo(dragStart.x, dragStart.y); ctx.lineTo(pos.x,pos.y); ctx.stroke(); } else if(tool==='square'){ const x=Math.min(dragStart.x,pos.x), y=Math.min(dragStart.y,pos.y), w=Math.abs(pos.x-dragStart.x), h=Math.abs(pos.y-dragStart.y); if(w>0&&h>0){ ctx.beginPath(); ctx.rect(x,y,w,h); ctx.stroke(); } } else if(tool==='highlight'){ const x=Math.min(dragStart.x,pos.x), y=Math.min(dragStart.y,pos.y), w=Math.abs(pos.x-dragStart.x), h=Math.abs(pos.y-dragStart.y); if(w>0&&h>0){ ctx.globalAlpha=0.4; ctx.fillRect(x,y,w,h); } } else if(tool==='blackboard'){ const x=Math.min(dragStart.x,pos.x), y=Math.min(dragStart.y,pos.y), w=Math.abs(pos.x-dragStart.x), h=Math.abs(pos.y-dragStart.y); if(w>0&&h>0){ ctx.fillStyle='#1a1a1a'; ctx.fillRect(x,y,w,h); } } else { const cx=(dragStart.x+pos.x)/2, cy=(dragStart.y+pos.y)/2, rx=Math.abs(pos.x-dragStart.x)/2, ry=Math.abs(pos.y-dragStart.y)/2; if(rx>0&&ry>0){ ctx.beginPath(); ctx.ellipse(cx,cy,rx,ry,0,0,Math.PI*2); ctx.stroke(); } } ctx.restore(); } }
  function onMouseUp(e){ if(!drawing) return; drawing=false; const pos=getPos(e); if(tool==='draw'){ if(currentPath.length===1) currentPath.push(currentPath[0]); actions.push({type:'draw', points:currentPath.slice(), color, lineWidth}); redoStack.length=0; currentPath=[]; } else if(tool==='arrow'){ actions.push({type:'arrow', x1:dragStart.x, y1:dragStart.y, x2:pos.x, y2:pos.y, color, lineWidth}); redoStack.length=0; replayAll(); } else if(tool==='square'){ const w=Math.abs(pos.x-dragStart.x), h=Math.abs(pos.y-dragStart.y); if(w>1&&h>1){ actions.push({type:'square', x1:dragStart.x, y1:dragStart.y, x2:pos.x, y2:pos.y, color, lineWidth}); redoStack.length=0; } replayAll(); } else if(tool==='circle'){ const rx=Math.abs(pos.x-dragStart.x)/2, ry=Math.abs(pos.y-dragStart.y)/2; if(rx>1&&ry>1){ actions.push({type:'circle', x1:dragStart.x, y1:dragStart.y, x2:pos.x, y2:pos.y, color, lineWidth}); redoStack.length=0; } replayAll(); } else if(tool==='line'){ const dx=Math.abs(pos.x-dragStart.x), dy=Math.abs(pos.y-dragStart.y); if(dx>1||dy>1){ actions.push({type:'line', x1:dragStart.x, y1:dragStart.y, x2:pos.x, y2:pos.y, color, lineWidth}); redoStack.length=0; } replayAll(); } else if(tool==='highlight'){ const w=Math.abs(pos.x-dragStart.x), h=Math.abs(pos.y-dragStart.y); if(w>1&&h>1){ actions.push({type:'highlight', x1:dragStart.x, y1:dragStart.y, x2:pos.x, y2:pos.y, color}); redoStack.length=0; } replayAll(); } else if(tool==='blackboard'){ const w=Math.abs(pos.x-dragStart.x), h=Math.abs(pos.y-dragStart.y); if(w>1&&h>1){ actions.push({type:'blackboard', x1:dragStart.x, y1:dragStart.y, x2:pos.x, y2:pos.y}); redoStack.length=0; } replayAll(); } dragStart=null; }
  function onKeyDown(e){ if(textEditing) return; const key=e.key.toLowerCase(); const mod=e.metaKey||e.ctrlKey; if(mod&&key==='a'){ e.preventDefault(); e.stopPropagation(); if(actions.length>0) enterSelectAll(); return; } if(allSelected&&(e.key==='Delete'||e.key==='Backspace')){ e.preventDefault(); e.stopPropagation(); actions.length=0; redoStack.length=0; exitSelectAll(); return; } if(allSelected&&e.key==='Escape'){ e.preventDefault(); e.stopPropagation(); exitSelectAll(); return; } if(allSelected) exitSelectAll(); if(mod&&key==='z'&&!e.shiftKey){ e.preventDefault(); e.stopPropagation(); if(actions.length){ redoStack.push(actions.pop()); replayAll(); } return; } if(mod&&(key==='y'||(key==='z'&&e.shiftKey))){ e.preventDefault(); e.stopPropagation(); if(redoStack.length){ actions.push(redoStack.pop()); replayAll(); } return; } if(!mod){ let handled=true; switch(key){ case 'd': setTool('draw'); break; case 'a': setTool('arrow'); break; case 's': setTool('square'); break; case 'c': setTool('circle'); break; case 'f': setTool('text'); break; case 'h': setTool('highlight'); break; case 'b': setTool('blackboard'); break; case 'l': setTool('line'); break; case 'n': setTool('callout'); break; case '1': setColor('#ff0000'); break; case '2': setColor('#2563eb'); break; case '3': setColor('#16a34a'); break; case '4': setColor('#eab308'); break; case '5': setColor('#d1d5db'); break; case '6': setColor('#6b7280'); break; case 'r': if(tool==='text'){ fontSize=Math.min(fontSize+2,72); } else { lineWidth=Math.min(lineWidth+1,20); localStorage.setItem('annotate_lineWidth', String(lineWidth)); } updateIndicatorWidth(); break; case 'e': if(tool==='text'){ fontSize=Math.max(fontSize-2,8); } else { lineWidth=Math.max(lineWidth-1,1); localStorage.setItem('annotate_lineWidth', String(lineWidth)); } updateIndicatorWidth(); break; case 'escape': if(document.getElementById('annotate-dialog')){ clearExitDialog(); teardown(); } else { showExitDialog(); } break; default: handled=false; } if(handled){ e.preventDefault(); e.stopPropagation(); } } }
  let indDrag=false, indMoved=false, indOff={x:0,y:0};
  indicator.addEventListener('mousedown',(e)=>{ e.stopPropagation(); indDrag=true; indMoved=false; indOff.x=e.clientX-indicator.getBoundingClientRect().left; indOff.y=e.clientY-indicator.getBoundingClientRect().top; });
  document.addEventListener('mousemove',(e)=>{ if(!indDrag) return; indMoved=true; indicator.style.left=(e.clientX-indOff.x)+'px'; indicator.style.top=(e.clientY-indOff.y)+'px'; indicator.style.right='auto'; indicator.style.bottom='auto'; });
  document.addEventListener('mouseup',()=>{ if(indDrag&&!indMoved) showHelpPopup(); indDrag=false; });
  root.addEventListener('wheel',(e)=>{ root.style.pointerEvents='none'; const target=document.elementFromPoint(e.clientX,e.clientY); root.style.pointerEvents=''; if(!target) return; let el=target; while(el&&el!==document.documentElement){ const style=window.getComputedStyle(el); const oy=style.overflowY; if((oy==='auto'||oy==='scroll')&&el.scrollHeight>el.clientHeight) break; el=el.parentElement; } if(el) el.scrollBy({left:e.deltaX, top:e.deltaY}); }, {passive:true});
  canvas.addEventListener('mousedown', onMouseDown); canvas.addEventListener('mousemove', onMouseMove); canvas.addEventListener('mouseup', onMouseUp); document.addEventListener('keydown', onKeyDown, true); window.addEventListener('resize', sizeCanvas); sizeCanvas();
  window.AnnotateMac = { active: true, teardown };
})();
"""
}

extension String {
    var jsEscaped: String {
        self
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "'", with: "\\'")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "")
    }
}
